# Generated by Django 3.1.3 on 2020-11-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201115_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='burger',
            field=models.ManyToManyField(blank=True, help_text='Select a burger for this set', to='main.Burger'),
        ),
        migrations.AlterField(
            model_name='set',
            name='drink',
            field=models.ManyToManyField(blank=True, help_text='Select a drink for this set', to='main.Drink'),
        ),
        migrations.AlterField(
            model_name='set',
            name='pizza',
            field=models.ManyToManyField(blank=True, help_text='Select a pizza for this set', to='main.Pizza'),
        ),
        migrations.AlterField(
            model_name='set',
            name='roll',
            field=models.ManyToManyField(blank=True, help_text='Select a rolls for this set', to='main.Roll'),
        ),
        migrations.AlterField(
            model_name='set',
            name='snack',
            field=models.ManyToManyField(blank=True, help_text='Select a rolls snack this set', to='main.Snack'),
        ),
    ]
